### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by rklocke**
- Adds unit tests for add_optimised_filtering.py, panels.py and vcf.py
- Removes CSQ string as an input and instead obtains the CSQ fields to split with bcftools +split-vep directly from the VCF header
- Now performs checks of the panel string given to ensure only one panel (or one panel plus HGNC IDs, or HGNCs alone) is provided and only searches for MOI information for the panel within the panel string
- Adds the INFO MOI field as 'NONE' for a variant if that gene is not in the dictionary we've made for our panel or the gene has no MOI info from PanelApp
- Fixes README so the gnomAD part of the bcftools filter string example is correct
- Removes read_in_csv() function in file_utils.py which is no longer used

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: 3 of 18 files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @rklocke)

___
*[`resources/tests/test_add_optimised_filtering.py` line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlScbo_61vyQyZ_XPfF:-NlScbo_61vyQyZ_XPfG:b-dwbmmm) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/b88195a86141fee1bf0a9403e029a0057e8379ca/resources/tests/test_add_optimised_filtering.py#L64)):*
> ```Python
>         with pytest.raises(AssertionError) as exc_info:
>             check_panel_string(test_input_bad)
>         assert str(exc_info.value) == expected_warning
> ```

`pytest.raises` has an optional `match` input to check that your raised error has the correct message, so this should be able to be written as:
```
with pytest.raises(AssertionError, match=expected_warning):
            check_panel_string(test_input_bad)
```



_Code quote:_
```Python
        with pytest.raises(AssertionError) as exc_info:
            check_panel_string(test_input_bad)
        assert str(exc_info.value) == expected_warning
```
___
*[`resources/tests/test_panels.py` line 19 at r2](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlSdRdq034ICgORmVSu:-NlSdRdq034ICgORmVSv:b-s1ov13) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/b88195a86141fee1bf0a9403e029a0057e8379ca/resources/tests/test_panels.py#L19)):*
> ```Python
> 
> 
> class TestParseGenePanels():
> ```

I am here, need to go do other things



_Code quote:_
```Python
class TestParseGenePanels():
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: 12 of 18 files reviewed, 11 unresolved discussions (waiting on @chrispyatt and @rklocke)

___
*[`resources/tests/test_vcf.py` line 62 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYo-1kABqsolH2s4b6:-NlYo-1kABqsolH2s4b7:bhnnir6) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L62)):*
> ```Python
>             vcf.bgzip(mock_vcf)
> ```

can we have a couple simple tests for `bcftools_filter()` too to check the subprocess call works and the assert is raised like you have for bgzip
___
*[`resources/tests/test_vcf.py` line 247 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYoKl77amidI-P23My:-NlYoKl77amidI-P23Mz:b-w8aq55) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L247)):*
> ```Python
>         assert os.path.exists(self.flagged_vcf)
> 
>         os.remove(self.flagged_vcf)
> ```

can we also have a few unit tests for `bcftools_remove_csq_annotation()`, and can you also add a couple of asserts to the function itself for the pre and post counts in subprocess calls, and test these raise as we expect

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, 2 of 3 files at r3, 2 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: 15 of 18 files reviewed, 12 unresolved discussions (waiting on @chrispyatt and @rklocke)

___
*[`resources/tests/test_panels.py` line 465 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYqRP-2hUIyjXMrGZo:-NlYqRP-2hUIyjXMrGZp:b-je4ub1) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_panels.py#L465)):*
> ```Python
>     def test_format_panel_info_if_genes_and_regions_above_conf_3(self):
>         """
>         Check empty dict created if no genes above conf 3 found
> ```

dict should be not empty in this case?



_Code quote:_
```Python
empty
```

**Review by chrispyatt — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 1 of 3 files at r3, 4 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: all files reviewed, 12 unresolved discussions (waiting on @rklocke)

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: 10 of 22 files reviewed, 11 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`.github/workflows/pytest.yml` line 2 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlTtG3-6HDB8-966T3y:-NlYu0su8OpCjAUi8g-B:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/.github/workflows/pytest.yml#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can be switched back to `pull_request`
</blockquote></details>

Done.
___
*[`resources/tests/test_add_optimised_filtering.py` line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlScbo_61vyQyZ_XPfF:-NlYu1jl9pchMWHueyTD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/b88195a86141fee1bf0a9403e029a0057e8379ca/resources/tests/test_add_optimised_filtering.py#L64)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`pytest.raises` has an optional `match` input to check that your raised error has the correct message, so this should be able to be written as:
```
with pytest.raises(AssertionError, match=expected_warning):
            check_panel_string(test_input_bad)
```
</blockquote></details>

Done.
___
*[`resources/tests/test_panels.py` line 19 at r2](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlSdRdq034ICgORmVSu:-NlYu4Hs2BeW7j4zJSht:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/b88195a86141fee1bf0a9403e029a0057e8379ca/resources/tests/test_panels.py#L19)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I am back
</blockquote></details>

Done.
___
*[`resources/tests/test_panels.py` line 112 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlTu0Lj2-AHcTvfcPoy:-NlYuBDp3rmi6zC2hweR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_panels.py#L112)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be `>1`?
</blockquote></details>

Done.
___
*[`resources/tests/test_panels.py` line 279 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlTuN382e6cFrprSu4v:-NlYuMoK6cDomWVhHGQ5:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_panels.py#L279)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

parentheses not needed for single line string
</blockquote></details>

Done.
___
*[`resources/tests/test_panels.py` line 465 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYqRP-2hUIyjXMrGZo:-NlYuXgC6GBO3aAo-sxC:b3lj3z8) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_panels.py#L465)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

dict should be not empty in this case?
</blockquote></details>

oops fixed 
___
*[`resources/tests/test_vcf.py` line 62 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYo-1kABqsolH2s4b6:-Nleb__F7ZurQlF_t1qs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L62)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we have a couple simple tests for `bcftools_filter()` too to check the subprocess call works and the assert is raised like you have for bgzip
</blockquote></details>

Done.
___
*[`resources/tests/test_vcf.py` line 87 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYfO23D-aEUiXffB2Z:-Nl_92wmDnbjqr2euGoS:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L87)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

instead of having a test with multiple asserts, consider either gathering up any errors or using pytest subtest: https://pypi.org/project/pytest-subtests/

as it currently is, if the first assertion fails the other parts of the test are not run
</blockquote></details>

Done.
___
*[`resources/tests/test_vcf.py` line 219 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYiXJiEmyzNkL9cQ8p:-NlgxuENDzIvLHJoWgAZ:bmoo3q9) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L219)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we add a test here that once the contents of the file are written, we can read them back in and show they are identical to what was passed as input to the function.

This might be a good thing to actually add a separate function to do this at run time too to verify the file hasn't been truncated or  anything like is done for workbooks: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/excel.py#L868

(this is fine to leave for another PR if you want to separate it from the tests)
</blockquote></details>

Added a separate function at runtime to check VCF isn't truncated and added test truncated VCF to check this raises assert as expected
___
*[`resources/tests/test_vcf.py` line 247 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYoKl77amidI-P23My:-NleVAx71wKx0mW936e0:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/tests/test_vcf.py#L247)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we also have a few unit tests for `bcftools_remove_csq_annotation()`, and can you also add a couple of asserts to the function itself for the pre and post counts in subprocess calls, and test these raise as we expect
</blockquote></details>

Done.
___
*[`resources/utils/panels.py` line 244 at r6](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-NlYluI830UwgB0UviB_:-NlbzqDW0t7jmknRfNXO:b6vedfb) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/4a0ea46a5f7e227b598396569afd4811af487f14/resources/utils/panels.py#L244)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this because an empty dict can be passed here?
</blockquote></details>

Yes, dict is empty if no panel with a specific ID is found in the PanelApp dump so that this will still work if just HGNCs are in the panel string (but will just annotate all the MOIs as 'NONE')

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 7 files at r5, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-:-NlhNuUDC4W43_MooRNr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
PR looks good to me and tests all pass :tada: 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11#-:-NlhNxLvEAuX7iWGCU2h:bffjzlv)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/11)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
